info = input('Digite algo: ')
print(f'O tipo desse valor é {type(info)}')
print(f'Só tem espaços? {info.isspace()}')
print(f'É um numero? {info.isnumeric()}')
print(f'É alfabetico? {info.isalpha()}')
print(f'É alfanumerico? {info.isalnum()}')
print(f'Está em minusculas? {info.islower()}')
print(f'Está em minusculas? {info.isupper()}')
print(f'Está captalizada? {info.istitle()}')